### ISSUE TITLE
Translation of "/page/"

### ISSUE THREAD

**Issue by mtx-z** [spatie/laravel-paginateroute#16]
Hey there !
Thanks for the great package.

I have an issue with the translation of the "page" segment. The "page" word is never translated, stay the same in every language. I published translation file for paginate-route (`resources/lang/vendors/paginateroute`) and edited them. I re-published multiple times already to be sure. 

My route is declared like so: `Route::paginate('/', ['as' => 'home', 'uses' => 'FrontendController@index']);`

If I try change the URL in my browser from `domain.com/en/page/2` to `domain.com/de/seite/2`, it goes 404. So the URL with translated "page" does not even exist. 

Anything i could have forgotten to do ? 

Thanks in advance !

**Comment by mtx-z** [comment]
any up ?

**Comment by sebastiandedeyne** [comment]
What Laravel version does this happen in?

In a tinker session, what's the output of `trans('paginateroute::paginateroute.page')` after setting the locale to German?

**Comment by mtx-z** [comment]
Hey, sorry for the delay. 

Issue occurs on Laravel 5.1.
The output of `trans('paginateroute::paginateroute.page')` is correct, and send back the "page" translation from `/lang/vendor/paginateroute/{local}/paginateroute.php` translation files (tested by changing the test URL `/{locale_code}/`, and so set the app locale value). 

But still:
- reaching the URL with the translated value falls in 404.
- it seems only the EN value is used for every language. If i update the EN value, all language "page" URL segment are using the EN value. Trying access URL with a translated "page" value and the related URL `/{locale_code}/` is 404.

Thanks

**Comment by AlexVanderbist** [comment]
Hi @mtx-z 

I suspect this problem is because the locale is changed after the route is already created with a certain `pageKeyword` (seite/page/...). 

The package only creates a route for the currently active locale and this happens _before_ any of the middlewares run. This means that the translated route is already created _before_ you change the locale to something else.

To get it working I'd recommend setting the current locale earlier on in the request life cycle. For example in the `boot()` method of the `AppServiceProvider` or even cleaner; make your own `LocaleServiceProvider` that gets the locale from the request/cookie/session/...

Good luck!

*On a side note: when I was testing this I noticed the latest version of the package (2.4.0) no longer works on Laravel 5.1. This means the latest working version of this package for Laravel 5.1 is 2.3.0.*

**Comment by noge075** [comment]
Hi!

I had the same issue. The base problem is, when you register the macros the base laravel session is not started, so the translater will be load the fallback language. 

You have some choice to resolve that like start the session before register the macros. I simply use the register method in my web.php before using any paginate method and it works good. 

The last problem is to add new languages still need to write to the vendor folder what not great. I tried to add  a new key "page" to resources/lang/{locale}/pagination.php, but it not worked.

I know that is not the best solution but it's work without any vendor changes.
